### ISSUE TITLE
When will the windows version be supported

### ISSUE THREAD

**Issue by Eurostarfan232** [RagingLightning/TSW3-LM#1] opened 2022-10-28 13:31 UTC
\<no Content\>

**Comment by RagingLightning** [comment] 2022-11-01 10:31
Coming from TSW2, I assume, that the tool technically supports the Xbox/MS-Store version. The only problem is finding the file, where the information is stored, because this is a bit more involved than with epic/steam. Without this functionality, it's basically impossible for the user to find fhe correct file to use.

If you have a MS-Store installation and are willing to help, please contact me on discord `RagingLightning#8192`, because finding that file will require a bit of back and forth.

**Comment by RagingLightning** [comment] 2023-01-22 12:46
now duplicate of #6

**Closed as completed by RagingLightning** 2023-01-22 12:46 UTC
Labels: enhancement, help wanted

**Comment by Peter-1800** [comment] 2023-08-25 17:18
Is there any plans yet to support the windows store version it's a real shame if there is a way to install them without using LM would be great but seems there's not! It took me ages to work out the MS Store version is why it was not working.....
